### ISSUE TITLE
CUDA out of memory exception

### ISSUE THREAD

**Issue by alexey3nemckovich** [AllenXiangX/Retro-FPN#6]
I am trying to test your model using dataset you recommended.
I am interested in PointTransformer + retro-FPN

Soon after starting training I get exception CUDA out of memory on this line of **retro_transformer.py:44**
`x_q = x_q.unsqueeze(1).repeat((1, self.n_samples, 1)).view(n, self.n_samples, self.n_groups, self.n_share_channels) + p_rq`

I tried to cut batch size to 1, but that didn't help.
I have GPU with 12 GB RAM. I believed that should be enough or I am wrong at this point?

**Comment by AllenXiangX** [comment]
That doesn't seem normal, batchsize 1 works for me on RTX 3090 gpu and it takes about 8G cuda memory (batch_size=1, workers=1, batch_size_val=1). Could you provide more information like the configuration file? Did the exception occur during training or evaluation, which epoch?

**Comment by alexey3nemckovich** [comment]
I am sorry for disinformation. I realized that I changed not proper config file. So with batch size=1 it seems to work. Thank you for quick response!
